### ISSUE TITLE
Minimal README/manual

### ISSUE THREAD

**Issue by wuschel** [longturn/games#4]
Hi, 

I just checked out _http://longturn.org/_ and _http://forum.longturn.org/_. Very nice modification of **Freeciv**. However, I wondered if there are any best practises on how to build, configure, and set up a server - especially for a **Longturn** game.

**Comment by lmoureaux** [comment]
For posterity, we now have such a guide at https://longturn.readthedocs.io/en/latest/Manuals/on-the-server.html.
